development:
  adapter: async

test:
  adapter: async

production:
# adapter: redis
#  url: redis://localhost:6379/1
  adapter: postgresql
  url: postgres://ktvhjuofejtkxv:8039b9d98e58b014775203cde2554b07cd70025221dbe3d1b3f279e7808c2821@ec2-184-73-189-190.compute-1.amazonaws.com:5432/dbn140it002qsg
#  channel_prefix: rails_project_c_production
